name: stereo_example
description: Demonstrates how to use the stereo plugin.

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 4.7.2
  path_provider: 0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  stereo:
    path: ../src

flutter:
  assets:
    - assets/songs/dubstep.mp3
    - assets/songs/pi.mp3
  fonts:
    - family: FontAwesome
      fonts:
        - asset: packages/font_awesome_flutter/fonts/fontawesome.woff
  uses-material-design: true
