name: stereo
description: A Flutter plugin for playing music on iOS and Android. Supports
    basic media controls (play, pause, stop, seek) and picking files from
    internal storage.
version: 1.0.2
author: 2find Team <2findteam@googlegroups.com>
homepage: https://github.com/2find/stereo

analyzer:
    strong-mode: true

flutter:
  plugin:
    androidPackage: com.twofind.stereo
    pluginClass: StereoPlugin
    iosPrefix: ST

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
